// The single data seam: every page/component reads the dataset through
// this module. Full element records come from the committed
// data-source/elements.json (synced from untded/untded-2005); the
// compact runtime index under /data/index.json is the same data in wire
// format (see scripts/lib/build-index.mjs).
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

export interface Representation {
  raw: string
  charset: string
  min_length: number
  max_length: number
}

export interface Provenance {
  page: number
}

export interface ElementRecord {
  tag: number
  name: string | null
  description: string | null
  representation: Representation | null
  change_tag: string
  status: 'active' | 'retired'
  old_name: string | null
  business_term: string | null
  notes: string | null
  bridges: string | null
  provenance: Provenance
}

export interface IndexRow {
  t: number
  n: string
  r: string
  c: string
  s: 'a' | 'r'
  k: number
}

interface DatasetFile {
  elements: ElementRecord[]
}

// The single data seam's shared reader: one cwd resolution (build-time
// chunks move, so import.meta.url breaks), one missing-file error mode.
// The other loaders (edifact, uncl, vocabulary) build on this.
export function loadJson<T>(file: string): T {
  return JSON.parse(readFileSync(resolve(process.cwd(), `data-source/${file}`), 'utf8')) as T
}

export type Category = { k: number; section: string; range: string; label: string }

// The nine categories, generated by the dataset (derived/categories.json)
// and synced into data-source/ — the dataset is the only writer. Labels are
// the source's own section titles, verbatim except for the display
// capitalisation applied here.
let categoryCache: readonly Category[] | null = null

export function loadCategories(): readonly Category[] {
  if (categoryCache === null) {
    const records = loadJson<Array<{ k: number; section: string; range: string; label: string }>>('categories.json')
    categoryCache = records.map((c) => ({
      ...c,
      label: c.label[0].toUpperCase() + c.label.slice(1),
    }))
  }
  return categoryCache
}

export function categoryOf(tag: number): Category {
  return loadCategories()[Math.floor(tag / 1000) - 1]
}

let cache: ElementRecord[] | null = null

export function loadElements(): ElementRecord[] {
  if (cache === null) {
    cache = (loadJson<DatasetFile>('elements.json')).elements
  }
  return cache
}

export function elementByTag(tag: number): ElementRecord | undefined {
  return loadElements().find((e) => e.tag === tag)
}

// Linked Data: nodes come verbatim from the dataset's untded.jsonld
// (generated by untded-2005's Untded::LinkedData) so the semantic shape
// has exactly one definition. The origin is the live site.
let jsonldCache: Record<string, unknown>[] | null = null

function loadJsonLdGraph(): Record<string, unknown>[] {
  if (jsonldCache === null) {
    const file = loadJson<{ '@graph': Record<string, unknown>[] }>('untded.jsonld')
    jsonldCache = file['@graph']
  }
  return jsonldCache
}

export function jsonldNode(id: string): Record<string, unknown> | undefined {
  return loadJsonLdGraph().find((n) => n['@id'] === id)
}
