// data-source/edifact-links.json — generated by the dataset's
// bin/join-edifact (tag join against the UN/EDIFACT D.05B segments
// mirror). Only elements referenced by D05B segments appear; absence
// is informational, not a mismatch.
import { loadJson } from './data'

export interface EdifactLink {
  tag: number
  edifact: { name: string; type: string; maxLength: number }
  reprRaw: string | null
  aligned: boolean
}

export function loadEdifactLinks(): Map<number, EdifactLink> {
  const doc = loadJson<{ links: EdifactLink[] }>('edifact-links.json')
  return new Map(doc.links.map((l: EdifactLink) => [l.tag, l]))
}
