// data-source/edifact-links.json — generated by the dataset's
// bin/join-edifact (tag join against the UN/EDIFACT D.05B segments
// mirror). Only elements referenced by D05B segments appear; absence
// is informational, not a mismatch.
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

export interface EdifactLink {
  tag: number
  edifact: { name: string; type: string; maxLength: number }
  reprRaw: string | null
  aligned: boolean
}

export function loadEdifactLinks(): Map<number, EdifactLink> {
  const doc = JSON.parse(
    readFileSync(resolve(process.cwd(), 'data-source/edifact-links.json'), 'utf8'),
  )
  return new Map(doc.links.map((l: EdifactLink) => [l.tag, l]))
}
