// Domain SSOT: how an element record becomes display language.
// Every label, category resolution and bridge parse in the site derives
// from here — components never re-encode this knowledge.
import type { ElementRecord } from './data'
import { href } from './site'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

export type Category = { k: number; section: string; range: string; label: string }

// The nine categories, generated by the dataset (derived/categories.json)
// and synced into data-source/ — the dataset is the only writer. Labels are
// the source's own section titles, verbatim except for the display
// capitalisation applied here. Read from cwd because import.meta.url breaks
// in build chunks (same as data.ts).
let categoryCache: readonly Category[] | null = null
export function loadCategories(): readonly Category[] {
  if (categoryCache === null) {
    const records = JSON.parse(
      readFileSync(resolve(process.cwd(), 'data-source/categories.json'), 'utf8'),
    ) as Array<{ k: number; section: string; range: string; label: string }>
    categoryCache = records.map((c) => ({
      ...c,
      label: c.label[0].toUpperCase() + c.label.slice(1),
    }))
  }
  return categoryCache
}

// Legend as printed in UNTDED 2005 section 4.1 (the source's own words,
// abridged); tags outside the printed legend (cd/cr/cdr) are annotated.
const CHANGE_TAG_LABELS: Record<string, string> = {
  add: 'Added',
  u: 'Undeleted (re-instated)',
  cn: 'Changed name',
  cnd: 'Changed name + description',
  cnr: 'Changed name + representation',
  cndr: 'Changed name + description + representation',
  x: 'Marked for deletion',
}

const OUTSIDE_LEGEND = new Set(['cd', 'cr', 'cdr'])

export interface ChangeTagInfo {
  label: string
  short: string
  outsideLegend: boolean
}

export function changeTagInfo(changeTag: string): ChangeTagInfo {
  return {
    label: CHANGE_TAG_LABELS[changeTag] ?? changeTag,
    short: changeTag,
    outsideLegend: OUTSIDE_LEGEND.has(changeTag),
  }
}


export function categoryOf(tag: number): Category {
  return loadCategories()[Math.floor(tag / 1000) - 1]
}

export function elementUrl(tag: number): string {
  return href(`/elements/${tag}`)
}

export interface Bridge {
  scheme: string
  detail: string
}

const BRIDGE_SCHEME = /(?:Inland Waterways B\/L|CIMP|UNLK|UNSM|EDIFACT|ODETTE|SWIFT|SAD|MAR|AWB|CMR|CIM|ICC|INV|ISO|B\/L):/g

// Bridge scheme expansions, verbatim from the publication's list of
// abbreviations (introduction, section 1.4); `editorial` marks the two
// not printed in that list.
export const BRIDGE_SCHEME_DEFS: Record<string, { text: string; source: 'publication' | 'editorial' }> = {
  UNLK: { text: 'United Nations Layout Key', source: 'publication' },
  SAD: { text: 'Single Administrative Document (EC and EFTA)', source: 'publication' },
  CIM: { text: 'Rail Consignment Note (CIM Convention)', source: 'publication' },
  CIMP: { text: 'IATA Cargo Interchange Message Procedures Manual (CARGO-IMP manual)', source: 'publication' },
  MAR: { text: 'IMO Model forms and ICS Standard Bill of Lading', source: 'publication' },
  AWB: { text: 'IATA Air Waybill', source: 'publication' },
  CMR: { text: 'Road Consignment Note (CMR Convention)', source: 'publication' },
  SWIFT: { text: 'Society for Worldwide Interbank Financial Telecommunication', source: 'publication' },
  ICC: { text: 'International Chamber of Commerce', source: 'publication' },
  INV: { text: 'United Nations Layout Key for Aligned Invoices', source: 'publication' },
  UNSM: { text: 'United Nations Standard Message (UN/EDIFACT)', source: 'publication' },
  ODETTE: { text: 'Organisation for Data Exchange by Tele Transmission in Europe (automotive EDI)', source: 'editorial' },
  'Inland Waterways B/L': { text: 'Bill of lading for inland waterways', source: 'editorial' },
}

// "UNLK: L 04, P 41-45 CIMP: (120): a1" -> per-scheme entries. The
// trailing colon is part of the match so a scheme word occurring inside
// a detail (e.g. "SAD: (SAD 1)") is not mistaken for a new entry.
export function parseBridges(bridges: string | null): Bridge[] {
  if (!bridges) return []
  const out: Bridge[] = []
  let match: RegExpExecArray | null
  let last = 0
  let lastScheme = ''
  BRIDGE_SCHEME.lastIndex = 0
  while ((match = BRIDGE_SCHEME.exec(bridges)) !== null) {
    if (lastScheme) {
      out.push({ scheme: lastScheme, detail: bridges.slice(last, match.index).trim() })
    }
    last = match.index + match[0].length
    lastScheme = match[0].slice(0, -1)
  }
  if (lastScheme) {
    out.push({ scheme: lastScheme, detail: bridges.slice(last).trim() })
  }
  return out
}

export type BridgeSegment =
  | { kind: 'format'; text: string }
  | { kind: 'lines'; from: number; to: number | null }
  | { kind: 'positions'; from: number; to: number | null }
  | { kind: 'text'; text: string }

// Structured reading of one bridge detail: the printed notation uses
// "L n" for the line on the form and "P n-n" for character positions
// (per the publication, section 4.1: ISO 3535 / UNLK), and a
// representation token (an..17) for the field format in an interchange
// protocol. Everything else is kept verbatim.
const BRIDGE_TOKEN = /\b(an\.\.\d+|a\.\.\d+|n\.\.\d+|an\d+|a\d+|n\d+)\b|\bL (\d+)(?:\s*-\s*(\d+))?\b|\bP (\d+)(?:\s*-\s*(\d+))?\b/g

export function formatBridgeDetail(detail: string): BridgeSegment[] {
  const out: BridgeSegment[] = []
  let last = 0
  let m: RegExpExecArray | null
  BRIDGE_TOKEN.lastIndex = 0
  while ((m = BRIDGE_TOKEN.exec(detail)) !== null) {
    if (m.index > last) out.push({ kind: 'text', text: detail.slice(last, m.index).trim() })
    if (m[1]) out.push({ kind: 'format', text: m[1] })
    else if (m[2]) out.push({ kind: 'lines', from: Number(m[2]), to: m[3] ? Number(m[3]) : null })
    else if (m[4]) out.push({ kind: 'positions', from: Number(m[4]), to: m[5] ? Number(m[5]) : null })
    last = m.index + m[0].length
  }
  if (last < detail.length) out.push({ kind: 'text', text: detail.slice(last).trim() })
  return out.filter((seg) => seg.kind !== 'text' || seg.text)
}

export function replacementPointer(element: ElementRecord, tags: Set<number>): number | null {
  if (element.status !== 'retired' || !element.notes) return null
  const refs = [...element.notes.matchAll(/\b\d{4}\b/g)].map((m) => Number(m[0]))
    .filter((n) => n !== element.tag && n > 699 && !(n >= 1970 && n <= 2099) && tags.has(n))
  return refs[0] ?? null
}

export function reprSummary(repr: ElementRecord['representation']): string {
  if (!repr) return '—'
  return `${repr.charset}${repr.min_length === repr.max_length ? repr.max_length : `..${repr.max_length}`}`
}

// Document-order neighbours (the printed table is tag-ordered except for
// two known inversions).
export function neighbours(
  tag: number,
  tags: number[],
): { prev: number | null; next: number | null } {
  const sorted = [...tags].sort((a, b) => a - b)
  const i = sorted.indexOf(tag)
  if (i === -1) return { prev: null, next: null }
  return { prev: i > 0 ? sorted[i - 1] : null, next: i < sorted.length - 1 ? sorted[i + 1] : null }
}

// UNTDED convention (section 4.2.2): the even tag carries the clear-text
// version, the following odd tag the coded value. Returns the
// counterpart's tag when both sides exist in this edition.
export function pairedTag(tag: number, tags: Set<number>): number | null {
  const partner = tag % 2 === 0 ? tag + 1 : tag - 1
  return partner > 999 && partner < 10000 && tags.has(partner) ? partner : null
}
