// data-source/uncl-coverage.json — generated by the dataset's
// bin/join-uncl (tag join against the UN/EDIFACT D.05B UNCL code-list
// mirror, references/edifact-D05B/codes.xml). Only coded active
// elements appear; absence is informational, not a mismatch.
import { loadJson } from './data'

export interface UnclLink {
  tag: number
  code_values: number
}

export function loadUnclCoverage(): Map<number, number> {
  const doc = loadJson<{ links: UnclLink[] }>('uncl-coverage.json')
  return new Map((doc.links as UnclLink[]).map((l) => [l.tag, l.code_values]))
}
