// data-source/uncl-coverage.json — generated by the dataset's
// bin/join-uncl (tag join against the UN/EDIFACT D.05B UNCL code-list
// mirror, references/edifact-D05B/codes.xml). Only coded active
// elements appear; absence is informational, not a mismatch.
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

export interface UnclLink {
  tag: number
  code_values: number
}

export function loadUnclCoverage(): Map<number, number> {
  const doc = JSON.parse(
    readFileSync(resolve(process.cwd(), 'data-source/uncl-coverage.json'), 'utf8'),
  )
  return new Map((doc.links as UnclLink[]).map((l) => [l.tag, l.code_values]))
}
