// data-source/vocabulary.json — generated by the dataset from the single
// vocabulary declaration (model/untded/vocabulary.rb); the /ontology
// page renders it without hand-maintaining anything.
import { loadJson } from './data'

export interface VocabClass {
  term: string
  comment: string
}

export interface VocabTerm {
  term: string
  iri: string
  group: string
  domain?: string
  comment?: string
}

export interface VocabularyDoc {
  namespace: string
  prefixes: Record<string, string>
  classes: VocabClass[]
  terms: VocabTerm[]
}

export function loadVocabulary(): VocabularyDoc {
  return loadJson<VocabularyDoc>('vocabulary.json')
}
